#app:
#    resource: "@ProductBundle/Controller/"
#    type:     annotation

film_create:
  path: /film/
  defaults: { _controller: \MyApp\Bundle\FilmBundle\Film\Controller\CreateFilmController::execute }
  methods: [POST]

film_update:
  path: /film/{id}/
  defaults: { _controller: \MyApp\Bundle\FilmBundle\Film\Controller\UpdateFilmController::execute }
  methods: [PUT]

film_list:
  path: /film/
  defaults: { _controller: \MyApp\Bundle\FilmBundle\Film\Controller\ListFilmController::execute }
  methods: [GET]

film_delete:
  path: /film/{id}/
  defaults: { _controller: \MyApp\Bundle\FilmBundle\Film\Controller\DeleteFilmController::execute }
  methods: [DELETE]


actor_create:
  path: /actor/
  defaults: { _controller: \MyApp\Bundle\FilmBundle\Actor\Controller\CreateActorController::execute }
  methods: [POST]
