#app:
#    resource: "@ProductBundle/Controller/"
#    type:     annotation

film_create:
  path: /film/
  defaults: { _controller: \MyApp\Bundle\FilmBundle\Film\Controller\CreateFilmController::execute }
  methods: [POST]


actor_create:
  path: /actor/
  defaults: { _controller: \MyApp\Bundle\FilmBundle\Actor\Controller\CreateActorController::execute }
  methods: [POST]








product_delete:
  path: /product/{id}/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Product\Controller\DeleteProductController::execute }
  methods: [DELETE]

product_update:
  path: /product/{id}/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Product\Controller\UpdateProductController::execute }
  methods: [PUT]

product_list:
  path: /product/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Product\Controller\ListProductsController::execute }
  methods: [GET]

owner_create:
  path: /owner/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Owner\Controller\CreateOwnerController::execute }
  methods: [POST]

owner_list:
  path: /owner/
  defaults: { _controller: \MyApp\Bundle\ProductBundle\Owner\Controller\ListOwnersController::execute }
  methods: [GET]
