# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
services:
  app.bundle.doctrineFilmRepository:
      class: Doctrine\ORM\EntityRepository
      factory: ["@doctrine.orm.entity_manager", getRepository]
      arguments: ["FilmBundle:Film"]

  app.bundle.doctrineActorRepository:
      class: Doctrine\ORM\EntityRepository
      factory: ["@doctrine.orm.entity_manager", getRepository]
      arguments: ["FilmBundle:Actor"]

  app.fileCache:
      class: Doctrine\Common\Cache\FilesystemCache
      arguments: ['%kernel.root_dir%/../var/temp/']

  app.cacheFilmRepository:
      class:     MyApp\Bundle\FilmBundle\Film\Repository\CacheFilmRepository
      decorates: app.bundle.doctrineFilmRepository
      arguments: ['@app.cacheFilmRepository.inner', '@app.fileCache']

  app.component.createFilm:
      class: MyApp\Component\Film\Application\CommandHandlers\Film\CreateFilm
      arguments: ["@app.cacheFilmRepository.inner", "@app.bundle.doctrineActorRepository"]

  app.component.updateFilm:
      class: MyApp\Component\Film\Application\CommandHandlers\Film\UpdateFilm
      arguments: ["@app.cacheFilmRepository.inner", "@app.bundle.doctrineActorRepository"]

  app.component.listFilm:
      class: MyApp\Component\Film\Application\CommandHandlers\Film\ListFilm
      arguments: ["@app.cacheFilmRepository.inner"]

  app.component.deleteFilm:
      class: MyApp\Component\Film\Application\CommandHandlers\Film\DeleteFilm
      arguments: ["@app.cacheFilmRepository.inner"]

  app.component.listOneFilm:
      class: MyApp\Component\Film\Application\CommandHandlers\Film\ListOneFilm
      arguments: ["@app.bundle.doctrineFilmRepository"]

  app.component.createActor:
      class: MyApp\Component\Film\Application\CommandHandlers\Actor\CreateActor
      arguments: ["@app.bundle.doctrineActorRepository"]

  app.component.listActor:
      class: MyApp\Component\Film\Application\CommandHandlers\Actor\ListActor
      arguments: ["@app.bundle.doctrineActorRepository"]

  app.component.deleteActor:
      class: MyApp\Component\Film\Application\CommandHandlers\Actor\DeleteActor
      arguments: ["@app.bundle.doctrineActorRepository"]

  app.component.listOneActor:
      class: MyApp\Component\Film\Application\CommandHandlers\Actor\ListOneActor
      arguments: ["@app.bundle.doctrineActorRepository"]

  app.locale_listener:
      class: MyApp\Bundle\FilmBundle\EventsListener\LocaleListener
      arguments: ['%kernel.default_locale%']
      tags:
          - { name: kernel.event_subscriber }

  my.listener:
      class: MyApp\Bundle\FilmBundle\EventsListener\PostPersistListener
      arguments: ['@app.fileCache']
      tags:
          - { name: doctrine.event_listener, event: postPersist }
          - { name: doctrine.event_listener, event: postRemove }
          - { name: doctrine.event_listener, event: postUpdate }
