MyApp\Component\Film\Domain\Actor:
    type: entity
    repositoryClass: MyApp\Bundle\FilmBundle\Actor\Repository\DoctrineActorRepository
    table: actor
    id:
        idactor:
            type: integer
            nullable: false
            options:
                unsigned: true
            id: true
            generator:
                strategy: IDENTITY
    fields:
        name:
            type: string
            nullable: false
            length: 255
            options:
                fixed: false
    lifecycleCallbacks: {  }
